### ISSUE TITLE
Wire energy

### ISSUE THREAD

**Issue by pakiko24** [nelliewu95/accelergy#4]
Hello,

First of all contratulations for your work. I think the community really lacked this kind of framework so far. 

I have been looking up accelergy and also its integration with CACTI or ALADIN. However, none of them report the energy consumed by a wire. I have seen one number in the table-based template, but it looks a random number to provide the user the capacity to change it. 

My question is, do you know any source to get the energy consumption of a wire given a certain length?

Thank you very much

**Comment by nelliewu95** [comment]
There is a rough wire energy calculation in Aladdin plugin https://github.com/nelliewu95/accelergy-aladdin-plug-in/blob/master/aladdin_table.py#L231 and it is based on capacitance we found in public sources. 

CACTI has some public technology parameters listed https://github.com/HewlettPackard/cacti/tree/master/tech_params , and I believe it also has some calculations of wire energy based on these parameters deep embedded in the source code. You can create a table-based plug-in using these parameters and feed it to Accelergy.

**Comment by pakiko24** [comment]
Thank you very much @nelliewu95 , your answer have really helped me. 

Francisco.
